# fly.toml app configuration file generated for union-ceremony-tq-wkq on 2025-05-04T14:07:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'union-ceremony-tq-wkq'
primary_region = 'lhr'

[build]

[[mounts]]
  source = 'ceremony'
  destination = '/ceremony'

[http_service]
  internal_port = 4919
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
